### ISSUE TITLE
Add Background Color to Weekend Columns

### ISSUE THREAD

**Issue by ghost** [mvan231/Scriptable#16]
Hello,

Excellent widget! Is it possible to add a background color to the weekend dates and change the font color of the day names, like the example below?

![B6B8CF0D-B6A4-4E24-BCFA-5AB3DC30BE09](https://user-images.githubusercontent.com/79196114/119482323-a4cc9580-bd4b-11eb-9972-3a77c5f72c08.jpeg)

**Comment by mvan231** [comment]
In the screenshot you shared, the day name row is all the same color, but you're wanting to be able to change just the color of the name and have a background color for the days of Saturday and Sunday?

Currently there is an option to change the color for Saturday and Sunday dates, but the row of the day names remains in the base color of the widget.

**Comment by ghost** [comment]
Yes I was looking to style the calendar as it is in the screenshot, with the day names all blue and the Sat/Sun columns shaded grey?

**Comment by mvan231** [comment]
I see now. I was thinking you meant to only change the day name color of Saturday and Sunday.

so instead of the text color of Saturday and Sunday being different from the rest, you want to be able to have it shaded in the background, right? If I implement this way, I would have to force it to disable the highlighting of dates based on completed reminders, but I'm betting that would be okay for you, right?

**Comment by ghost** [comment]
Yes that would be great.

**Comment by mvan231** [comment]
Something like this? 
![0BFCF31E-8CA7-4F8D-A401-880A056E1AAB](https://user-images.githubusercontent.com/50910610/120119619-b3a9b280-c166-11eb-9c65-0f83e5884561.jpeg)

**Comment by mtoutkast** [comment]
👍🏾 that look amazing

**Comment by mvan231** [comment]
I'll make sure to put it in the upcoming update

**Comment by ghost** [comment]
That’s great, thank you

**Comment by mvan231** [comment]
Wonderful! I'm going to be uploading the new version today.
